### ISSUE TITLE
Documentation in README is for Master branch, not released gem

### ISSUE THREAD

**Issue by dkam** [hakanensari/ebay-ruby#4]
Hi there - thanks for making this library!

I discovered that the documentation for `Ebay.browser` is for the master branch, not the released v0.3.3.

Master branch contains:

```ruby
  # Returns a {Ebay::Browse#initialize Browse API} instance
  def self.browse(**params)
    Browse.new(**params)
  end
```

Which allows the `Ebay.browse` call, however this doesn't work in v0.3.3 as it's missing this code.  Maybe push a new version?

Cheers,
Dan

**Comment by hakanensari** [comment]
Will cut a new gem momentarily 👍
