### ISSUE TITLE
Add option to set marketplace_id for Ebay.browse

### ISSUE THREAD

**Issue by dkam** [hakanensari/ebay-ruby#5]
Hi there - thanks again for this gem.
I need to use the Ebay.browse functionality and would like to add the `X-EBAY-C-MARKETPLACE-ID`  header. 

I don't use any other Ebay functionality, so I'm not sure if it would be useful elsewhere, but for browse, I was thinking of adding market_id to the Browse#initialize method (defaulting to EBAY_US), set an instance variable and include the header in build_headers. In my use case, I'll set / change the marketplace often and it makes sense ( to me ) for it to be a Browse attribute.   If this solution is OK for you, I can submit a pull request.

```ruby
    def build_headers
      { 'AUTHORIZATION' => "Bearer #{access_token}",
        'X-EBAY-C-MARKETPLACE-ID' => market_id,
        'X-EBAY-C-ENDUSERCTX' => build_ebay_enduser_context }
    end
```

Cheers,
Dan

**Comment by hakanensari** [comment]
I just skimmed through the API docs; correct me if I'm wrong, but it seems this header is only required (and used?) by `#check_compatibility`? This must be why I implemented it as an argument on that method [here](https://github.com/hakanensari/ebay-ruby/blob/main/lib/ebay/browse.rb#L115-L128).

If this is useful to share across the other methods, by all means, yes, feel free to extract this into an instance attribute.

**Comment by dkam** [comment]
Yeah, it doesn't seem to be documented much at all. [This is where I found it](https://developer.ebay.com/api-docs/static/rest-request-components.html#headers). Without setting the header, all the results are for ebay.com, however if I set it to EBAY_AU then I get results for ebay.com.au, EBAY_GB -> ebay.co.uk etc.

Note in these examples,  **country** and **deliveryCountry** are set to **AU**

With no Marketplace header: 

```ruby
request = Ebay.browse(campaign_id: '5336455328', country: 'AU', access_token: access_token)
response = request.search(gtin: '9781408856772', filter: "deliveryCountry:AU,conditions:NEW")
data = JSON.parse(response.body.to_s)
data.dig('itemSummaries',0, 'itemWebUrl')
=> "https://www.ebay.com/itm/Harry-Potter-The-Complete-Collection-Box-Set-Paperback-Edition-by-J-K-Rowlin/373402177739?hash=item56f08110cb:g:svUAAOSwZcRf4lmj"
```

With Marketplace header set to EBAY_AU
```ruby
request = Ebay.browse(campaign_id: '5336455328', country: 'AU', access_token: access_token, market_id: 'EBAY_AU')
response = request.search(gtin: '9781408856772', filter: "deliveryCountry:AU,conditions:NEW")
data = JSON.parse(response.body.to_s)
data.dig('itemSummaries',0, 'itemWebUrl')
=> "https://www.ebay.com.au/itm/Harry-Potter-Box-Set-by-J-K-Rowling/113812903370?hash=item1a7fc715ca:g:MHYAAOSwbmVdljYO"
```
Marketplace header set to EBAY_GB,
```ruby
request = Ebay.browse(campaign_id: '5336455328', country: 'AU', access_token: access_token, market_id: 'EBAY_GB')
response = request.search(gtin: '9781408856772', filter: "deliveryCountry:AU,conditions:NEW")
data = JSON.parse(response.body.to_s)
data.dig('itemSummaries',0, 'itemWebUrl')
=> "https://www.ebay.co.uk/itm/Harry-Potter-The-Complete-Collection-7-Book-Boxset-7-Years-Used-But-Excellent/284171234577?hash=item4229eced11:g:UXkAAOSw7fJgGqgA"
```

**Comment by hakanensari** [comment]
Thanks, Dan. I merged your pull requests and will cut a new gem shortly.

**Comment by dkam** [comment]
Hi - mind cutting a new gem with the browse changes?

**Comment by hakanensari** [comment]
@dkam just did; I also added you as collaborator here and on Rubygems.

**Comment by dkam** [comment]
That's awesome - Thanks!
