### ISSUE TITLE
Key Not Found: Access Token during Oauth client credentials grant

### ISSUE THREAD

**Issue by wrburgess** [hakanensari/ebay-ruby#8]
## Versions

```
ruby "3.1.2"
gem "rails", "7.0.4"
gem "ebay-ruby", "0.4.1"
```

## Code Example

```
access_token = Ebay::Oauth::ClientCredentialsGrant.new.mint_access_token
request = Ebay.browse(campaign_id: '123', country: 'US', zip: '19406',
                      access_token: access_token, market_id: 'EBAY_US')
```

## Error Message

```
/Users/username/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ebay-ruby-0.4.1/lib/ebay/oauth/client_credentials_grant.rb:33:in `fetch': key not found: "access_token" (KeyError)
```

**Comment by dkam** [comment]
Hi there,  
    Have you set the app_id / dev_id / cert_id values? 

You can check them in `bin/console` with `puts Ebay::Config.app_id`

**Comment by dkam** [comment]
Hey @hakanensari, Even if it's not the case with this issue, I think we need to handle the case when authentication fails better.  How would you feel about raising a new error, `Error  < StandardError` with the message: "Unauthenticated: #{response.dig('error_description')}" being raised when mint_access_token fails?  In this case we'd get:

Unauthenticated: client authentication failed (Ebay::Error)

**Comment by wrburgess** [comment]
Yes. I can use the Find API with those credentials successfully.

**Comment by hakanensari** [comment]
@dkam yes, it would be great to handle errors here. Please have a go if you would like to write this!

**Comment by wrburgess** [comment]
I'm under the impression that I have the authentication working because this setup works for Find (token not needed), but fails for Browse (token needed). Not sure if I'm looking at documentation incorrectly, though.

This works for the Find API:

```
    Ebay.configure do |config|
      config.app_id = Rails.application.credentials.dig(:ebay_app_id)
      config.dev_id = Rails.application.credentials.dig(:ebay_dev_id)
      config.cert_id = Rails.application.credentials.dig(:ebay_cert_id)
    end

    request = Ebay.finding(response_data_format: "JSON").sandbox
    
    response = request.find_items_by_keywords("iphone")
```

This fails for the Browse API:

```
    Ebay.configure do |config|
      config.app_id = Rails.application.credentials.dig(:ebay_app_id)
      config.dev_id = Rails.application.credentials.dig(:ebay_dev_id)
      config.cert_id = Rails.application.credentials.dig(:ebay_cert_id)
    end

    access_token = Ebay::Oauth::ClientCredentialsGrant.new.mint_access_token
    
    request = Ebay.browse(
      access_token: access_token,
      campaign_id: '123',
      country: 'US',
      zip: '19406',
      market_id: 'EBAY_US'
    ).sandbox

    response = request.search(q: 'iphone')
```

Error:

```
gems/ebay-ruby-0.4.1/lib/ebay/oauth/client_credentials_grant.rb:33:
in `fetch': key not found: "access_token" (KeyError)
```

**Comment by wrburgess** [comment]
Just to add, when using debugger this is what's returned when firing the Oath grant (values obfuscated).

I'm not sure why my `dev_id` is not included in what's returned.

```
(ruby) Ebay::Oauth::ClientCredentialsGrant.new

#<Ebay::Oauth::ClientCredentialsGrant:0x00000001137fd460
 @app_id="xxxxxx-xxxxx-SBX-xxxxxxxxx-xxxxxxx",
 @cert_id="SBX-xxxxxxx-xxxx-4xxx-8xxx-3xxx">
```

**Comment by hakanensari** [comment]
I've gone ahead and implemented error handling. I didn't include `{response.dig('error_description')}` in the message so we handle other types of errors where this may not be available.

**Comment by wrburgess** [comment]
¯\_(ツ)_/¯

**Comment by hakanensari** [comment]
@wrburgess Sorry, I'm reopening this as the commit handles the obscure error but doesn't answer your original question.

`dev_id` is not included because [that's not required in this particular call](https://github.com/hakanensari/ebay-ruby/blob/main/lib/ebay/oauth/client_credentials_grant.rb#L26).

I'm guessing there's an issue with your credentials when minting the access token. Perhaps you're using the sandbox ones instead of production or vice versa?

Hope that helps!

**Comment by wrburgess** [comment]
I was trying to use the sandbox with sandbox credentials, but still getting nowhere.

**Comment by hakanensari** [comment]
I think you are hitting production 🤔

To sandbox, you need to:

```ruby
access_token = Ebay::Oauth::ClientCredentialsGrant.new.sandbox.mint_access_token
```

**Comment by wrburgess** [comment]
@hakanensari that indeed did the trick. Thank you.

I missed how to retrieve a sandbox token in the documentation, I guess.
